{
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/akbar527/Akbar/blob/Akbar527/6_RecA_SHAP_ADMET_Interpretability_Workflow_FIXED.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "markdown",
      "id": "f238c85d",
      "metadata": {
        "id": "f238c85d"
      },
      "source": [
        "# RecA SHAP + ADMET Interpretability Workflow\n",
        "\n",
        "Combined SHAP interpretability, ROC/confusion matrix plotting, ADMET heuristic screening, and SHAP waterfall analysis."
      ]
    },
    {
      "cell_type": "markdown",
      "id": "e3ec3918",
      "metadata": {
        "id": "e3ec3918"
      },
      "source": [
        "## 06_Feature_importance_SHAP_plots.py"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install catboost"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "CLtqZJwr1HZO",
        "outputId": "3f3a7576-cbc3-44de-b52c-dd4c1f954c85"
      },
      "id": "CLtqZJwr1HZO",
      "execution_count": 5,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Requirement already satisfied: catboost in /usr/local/lib/python3.12/dist-packages (1.2.10)\n",
            "Requirement already satisfied: graphviz in /usr/local/lib/python3.12/dist-packages (from catboost) (0.21)\n",
            "Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from catboost) (3.10.0)\n",
            "Requirement already satisfied: numpy<3.0,>=1.16.0 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.0.2)\n",
            "Requirement already satisfied: pandas<4.0,>=0.24 in /usr/local/lib/python3.12/dist-packages (from catboost) (2.2.2)\n",
            "Requirement already satisfied: scipy in /usr/local/lib/python3.12/dist-packages (from catboost) (1.16.3)\n",
            "Requirement already satisfied: plotly in /usr/local/lib/python3.12/dist-packages (from catboost) (5.24.1)\n",
            "Requirement already satisfied: six in /usr/local/lib/python3.12/dist-packages (from catboost) (1.17.0)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=0.24->catboost) (2026.2)\n",
            "Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.3.3)\n",
            "Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (0.12.1)\n",
            "Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (4.63.0)\n",
            "Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (1.5.0)\n",
            "Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (26.2)\n",
            "Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (11.3.0)\n",
            "Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->catboost) (3.3.2)\n",
            "Requirement already satisfied: tenacity>=6.2.0 in /usr/local/lib/python3.12/dist-packages (from plotly->catboost) (9.1.4)\n"
          ]
        }
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 12,
      "id": "31785e74",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "31785e74",
        "outputId": "cb5cda58-c04f-46dd-9f74-ec7a2dc5508e"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Training SVM...\n",
            "Training RandomForest...\n",
            "Training XGBoost...\n",
            "Training CatBoost...\n",
            "          model  accuracy  precision    recall  f1_score   roc_auc\n",
            "0           SVM  0.857143   0.894737  0.809524  0.850000  0.927186\n",
            "1       XGBoost  0.817460   0.822581  0.809524  0.816000  0.918871\n",
            "2  RandomForest  0.817460   0.884615  0.730159  0.800000  0.898967\n",
            "3      CatBoost  0.833333   0.875000  0.777778  0.823529  0.895188\n",
            "\n",
            "SHAP analysis completed.\n",
            "Outputs saved to:\n",
            "/content/outputs/feature_importance_shap\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "\"\"\"Optimized-model plotting and SHAP interpretability stage for RecA-TB.\n",
        "\n",
        "Recent reference-backed methodology (2021-2025):\n",
        "- Niazi and Mariam (2023), machine-learning-based chemoinformatics review.\n",
        "- Qi et al. (2024), machine learning in drug discovery.\n",
        "- Catacutan et al. (2024), machine learning in preclinical drug discovery.\n",
        "- Wang et al. (2024), comparative feature-selection strategies.\n",
        "- Vimbi et al. (2024), LIME/SHAP systematic review.\n",
        "- Rosenblatt et al. (2024), data leakage inflates prediction performance.\n",
        "\n",
        "This script rebuilds the optimized model comparison plots and derives SHAP-based\n",
        "global interpretability outputs for the best-performing models.\n",
        "\n",
        "See feature_importance_recent_references.md for full citations and links.\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "from pathlib import Path\n",
        "\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import shap\n",
        "\n",
        "from catboost import CatBoostClassifier\n",
        "from sklearn.compose import ColumnTransformer\n",
        "from sklearn.ensemble import RandomForestClassifier\n",
        "from sklearn.impute import SimpleImputer\n",
        "from sklearn.metrics import (\n",
        "    accuracy_score,\n",
        "    confusion_matrix,\n",
        "    f1_score,\n",
        "    precision_score,\n",
        "    recall_score,\n",
        "    roc_auc_score,\n",
        "    roc_curve,\n",
        ")\n",
        "from sklearn.model_selection import train_test_split\n",
        "from sklearn.pipeline import Pipeline\n",
        "from sklearn.preprocessing import StandardScaler\n",
        "from sklearn.svm import SVC\n",
        "from xgboost import XGBClassifier\n",
        "\n",
        "\n",
        "# Check if running in Google Colab\n",
        "if 'google.colab' in str(get_ipython()):\n",
        "    SCRIPT_DIR = Path('/content')\n",
        "else:\n",
        "    SCRIPT_DIR = Path(__file__).resolve().parent\n",
        "\n",
        "LOW_VARIANCE_FILE = (\n",
        "    SCRIPT_DIR\n",
        "    / \"03_recA_low_variance_filtered.csv\"\n",
        ")\n",
        "\n",
        "RANKING_FILE = (\n",
        "    SCRIPT_DIR\n",
        "    / \"03_recA_fscore_ranking.csv\"\n",
        ")\n",
        "\n",
        "METADATA_FILE = (\n",
        "    SCRIPT_DIR\n",
        "    / \"recA_molecule_metadata.csv\"\n",
        ")\n",
        "\n",
        "OUTPUT_DIR = (\n",
        "    SCRIPT_DIR\n",
        "    / \"outputs\"\n",
        "    / \"feature_importance_shap\"\n",
        ")\n",
        "\n",
        "TOP_K = 100\n",
        "TEST_SIZE = 0.2\n",
        "RANDOM_STATE = 42\n",
        "\n",
        "META_COLUMNS = [\n",
        "    \"Name\",\n",
        "    \"canonical_smiles\",\n",
        "    \"bioactivity_class\",\n",
        "    \"class\",\n",
        "]\n",
        "\n",
        "DESCRIPTOR_COLUMNS = [\n",
        "    \"full_mwt\",\n",
        "    \"alogp\",\n",
        "    \"psa\",\n",
        "    \"hba\",\n",
        "    \"hbd\",\n",
        "    \"rtb\",\n",
        "    \"aromatic_rings\",\n",
        "]\n",
        "\n",
        "\n",
        "def check_file_exists(path: Path) -> None:\n",
        "    if not path.exists():\n",
        "        raise FileNotFoundError(f\"File not found:\\n{path}\")\n",
        "\n",
        "\n",
        "def load_dataset(\n",
        "    top_k: int = TOP_K,\n",
        ") -> tuple[pd.DataFrame, pd.Series, list[str], list[str]]:\n",
        "    check_file_exists(LOW_VARIANCE_FILE)\n",
        "    check_file_exists(RANKING_FILE)\n",
        "    check_file_exists(METADATA_FILE)\n",
        "\n",
        "    low_variance = pd.read_csv(LOW_VARIANCE_FILE)\n",
        "    ranking = pd.read_csv(RANKING_FILE)\n",
        "    metadata = pd.read_csv(METADATA_FILE)\n",
        "\n",
        "    fingerprint_features = [\n",
        "        feature\n",
        "        for feature in ranking[\"feature\"].head(top_k).tolist()\n",
        "        if feature in low_variance.columns\n",
        "    ]\n",
        "\n",
        "    descriptors = metadata[\n",
        "        [\"molecule_chembl_id\", *DESCRIPTOR_COLUMNS]\n",
        "    ].rename(columns={\"molecule_chembl_id\": \"Name\"})\n",
        "\n",
        "    merged = low_variance.merge(\n",
        "        descriptors,\n",
        "        on=\"Name\",\n",
        "        how=\"left\",\n",
        "    )\n",
        "\n",
        "    descriptor_features = [\n",
        "        column\n",
        "        for column in DESCRIPTOR_COLUMNS\n",
        "        if column in merged.columns and merged[column].notna().any()\n",
        "    ]\n",
        "\n",
        "    x = (\n",
        "        merged[fingerprint_features + descriptor_features]\n",
        "        .apply(pd.to_numeric, errors=\"coerce\")\n",
        "        .replace([np.inf, -np.inf], np.nan)\n",
        "    )\n",
        "\n",
        "    y = merged[\"class\"].astype(int)\n",
        "\n",
        "    return (\n",
        "        x,\n",
        "        y,\n",
        "        fingerprint_features,\n",
        "        descriptor_features,\n",
        "    )\n",
        "\n",
        "\n",
        "def build_preprocessor(\n",
        "    fingerprint_features: list[str],\n",
        "    descriptor_features: list[str],\n",
        "    scale_descriptors: bool,\n",
        ") -> ColumnTransformer:\n",
        "    if scale_descriptors:\n",
        "        descriptor_transformer = Pipeline(\n",
        "            [\n",
        "                (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
        "                (\"scaler\", StandardScaler()),\n",
        "            ]\n",
        "        )\n",
        "    else:\n",
        "        descriptor_transformer = Pipeline(\n",
        "            [\n",
        "                (\"imputer\", SimpleImputer(strategy=\"median\")),\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    return ColumnTransformer(\n",
        "        [\n",
        "            (\n",
        "                \"descriptor_block\",\n",
        "                descriptor_transformer,\n",
        "                descriptor_features,\n",
        "            ),\n",
        "            (\n",
        "                \"fingerprint_block\",\n",
        "                \"passthrough\",\n",
        "                fingerprint_features,\n",
        "            ),\n",
        "        ],\n",
        "        remainder=\"drop\",\n",
        "    )\n",
        "\n",
        "\n",
        "def build_models(\n",
        "    fingerprint_features: list[str],\n",
        "    descriptor_features: list[str],\n",
        ") -> dict[str, Pipeline]:\n",
        "    return {\n",
        "        \"SVM\": Pipeline(\n",
        "            [\n",
        "                (\n",
        "                    \"preprocessor\",\n",
        "                    build_preprocessor(\n",
        "                        fingerprint_features,\n",
        "                        descriptor_features,\n",
        "                        scale_descriptors=True,\n",
        "                    ),\n",
        "                ),\n",
        "                (\n",
        "                    \"model\",\n",
        "                    SVC(\n",
        "                        kernel=\"rbf\",\n",
        "                        C=2,\n",
        "                        gamma=\"scale\",\n",
        "                        probability=True,\n",
        "                        class_weight=\"balanced\",\n",
        "                        random_state=RANDOM_STATE,\n",
        "                    ),\n",
        "                ),\n",
        "            ]\n",
        "        ),\n",
        "        \"RandomForest\": Pipeline(\n",
        "            [\n",
        "                (\n",
        "                    \"preprocessor\",\n",
        "                    build_preprocessor(\n",
        "                        fingerprint_features,\n",
        "                        descriptor_features,\n",
        "                        scale_descriptors=False,\n",
        "                    ),\n",
        "                ),\n",
        "                (\n",
        "                    \"model\",\n",
        "                    RandomForestClassifier(\n",
        "                        n_estimators=400,\n",
        "                        min_samples_split=5,\n",
        "                        min_samples_leaf=4,\n",
        "                        class_weight=\"balanced_subsample\",\n",
        "                        random_state=RANDOM_STATE,\n",
        "                        n_jobs=-1,\n",
        "                    ),\n",
        "                ),\n",
        "            ]\n",
        "        ),\n",
        "        \"XGBoost\": Pipeline(\n",
        "            [\n",
        "                (\n",
        "                    \"preprocessor\",\n",
        "                    build_preprocessor(\n",
        "                        fingerprint_features,\n",
        "                        descriptor_features,\n",
        "                        scale_descriptors=False,\n",
        "                    ),\n",
        "                ),\n",
        "                (\n",
        "                    \"model\",\n",
        "                    XGBClassifier(\n",
        "                        n_estimators=250,\n",
        "                        max_depth=5,\n",
        "                        learning_rate=0.08,\n",
        "                        subsample=0.8,\n",
        "                        colsample_bytree=0.9,\n",
        "                        min_child_weight=3,\n",
        "                        reg_lambda=2,\n",
        "                        eval_metric=\"logloss\",\n",
        "                        random_state=RANDOM_STATE,\n",
        "                        n_jobs=1,\n",
        "                    ),\n",
        "                ),\n",
        "            ]\n",
        "        ),\n",
        "        \"CatBoost\": Pipeline(\n",
        "            [\n",
        "                (\n",
        "                    \"preprocessor\",\n",
        "                    build_preprocessor(\n",
        "                        fingerprint_features,\n",
        "                        descriptor_features,\n",
        "                        scale_descriptors=False,\n",
        "                    ),\n",
        "                ),\n",
        "                (\n",
        "                    \"model\",\n",
        "                    CatBoostClassifier(\n",
        "                        iterations=400,\n",
        "                        learning_rate=0.05,\n",
        "                        depth=6,\n",
        "                        random_seed=RANDOM_STATE,\n",
        "                        verbose=False,\n",
        "                    ),\n",
        "                ),\n",
        "            ]\n",
        "        ),\n",
        "    }\n",
        "\n",
        "\n",
        "def plot_confusion_matrix(\n",
        "    cm: np.ndarray,\n",
        "    model_name: str,\n",
        "    output_file: Path,\n",
        ") -> None:\n",
        "    fig, ax = plt.subplots(figsize=(6.8, 5.4))\n",
        "\n",
        "    image = ax.imshow(cm, interpolation=\"nearest\")\n",
        "    plt.colorbar(image, ax=ax)\n",
        "\n",
        "    for i in range(cm.shape[0]):\n",
        "        for j in range(cm.shape[1]):\n",
        "            ax.text(\n",
        "                j,\n",
        "                i,\n",
        "                str(cm[i, j]),\n",
        "                ha=\"center\",\n",
        "                va=\"center\",\n",
        "                fontsize=12,\n",
        "            )\n",
        "\n",
        "    ax.set_title(f\"{model_name} Confusion Matrix\")\n",
        "    ax.set_xlabel(\"Predicted\")\n",
        "    ax.set_ylabel(\"Actual\")\n",
        "\n",
        "    plt.tight_layout()\n",
        "    fig.savefig(output_file, dpi=300, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "\n",
        "def plot_roc_curve(\n",
        "    y_true,\n",
        "    y_score,\n",
        "    model_name: str,\n",
        "    output_file: Path,\n",
        ") -> float:\n",
        "    fpr, tpr, _ = roc_curve(y_true, y_score)\n",
        "    auc = roc_auc_score(y_true, y_score)\n",
        "\n",
        "    fig, ax = plt.subplots(figsize=(6.8, 5.4))\n",
        "\n",
        "    ax.plot(fpr, tpr, lw=2, label=f\"AUC = {auc:.3f}\")\n",
        "    ax.plot([0, 1], [0, 1], linestyle=\"--\")\n",
        "\n",
        "    ax.set_xlabel(\"False Positive Rate\")\n",
        "    ax.set_ylabel(\"True Positive Rate\")\n",
        "    ax.set_title(f\"{model_name} ROC Curve\")\n",
        "\n",
        "    ax.legend()\n",
        "\n",
        "    plt.tight_layout()\n",
        "    fig.savefig(output_file, dpi=300, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "    return auc\n",
        "\n",
        "\n",
        "def get_transformed_dataframe(\n",
        "    model: Pipeline,\n",
        "    x: pd.DataFrame,\n",
        "    fingerprint_features: list[str],\n",
        "    descriptor_features: list[str],\n",
        ") -> pd.DataFrame:\n",
        "    transformed = model.named_steps[\"preprocessor\"].transform(x)\n",
        "\n",
        "    if hasattr(transformed, \"toarray\"):\n",
        "        transformed = transformed.toarray()\n",
        "\n",
        "    feature_names = descriptor_features + fingerprint_features\n",
        "\n",
        "    return pd.DataFrame(\n",
        "        transformed,\n",
        "        columns=feature_names,\n",
        "        index=x.index,\n",
        "    )\n",
        "\n",
        "\n",
        "def generate_shap_summary(\n",
        "    model: Pipeline,\n",
        "    x_test: pd.DataFrame,\n",
        "    fingerprint_features: list[str],\n",
        "    descriptor_features: list[str],\n",
        "    model_name: str,\n",
        ") -> None:\n",
        "    transformed_test = get_transformed_dataframe(\n",
        "        model,\n",
        "        x_test,\n",
        "        fingerprint_features,\n",
        "        descriptor_features,\n",
        "    )\n",
        "\n",
        "    base_model = model.named_steps[\"model\"]\n",
        "\n",
        "    explainer = shap.TreeExplainer(base_model)\n",
        "\n",
        "    shap_values = explainer.shap_values(transformed_test)\n",
        "\n",
        "    if isinstance(shap_values, list):\n",
        "        shap_values = shap_values[1]\n",
        "\n",
        "    shap_array = np.asarray(shap_values)\n",
        "\n",
        "    importance = pd.DataFrame(\n",
        "        {\n",
        "            \"feature\": transformed_test.columns,\n",
        "            \"mean_abs_shap\": np.abs(shap_array).mean(axis=0),\n",
        "        }\n",
        "    ).sort_values(\n",
        "        \"mean_abs_shap\",\n",
        "        ascending=False,\n",
        "    )\n",
        "\n",
        "    importance.to_csv(\n",
        "        OUTPUT_DIR / f\"{model_name.lower()}_shap_importance.csv\",\n",
        "        index=False,\n",
        "    )\n",
        "\n",
        "    plt.figure(figsize=(8.5, 6.2))\n",
        "\n",
        "    shap.summary_plot(\n",
        "        shap_array,\n",
        "        transformed_test,\n",
        "        show=False,\n",
        "        max_display=15,\n",
        "    )\n",
        "\n",
        "    plt.tight_layout()\n",
        "\n",
        "    plt.savefig(\n",
        "        OUTPUT_DIR / f\"{model_name.lower()}_shap_summary.png\",\n",
        "        dpi=300,\n",
        "        bbox_inches=\"tight\",\n",
        "    )\n",
        "\n",
        "    plt.close()\n",
        "\n",
        "\n",
        "def main() -> None:\n",
        "    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "    (\n",
        "        x,\n",
        "        y,\n",
        "        fingerprint_features,\n",
        "        descriptor_features,\n",
        "    ) = load_dataset()\n",
        "\n",
        "    x_train, x_test, y_train, y_test = train_test_split(\n",
        "        x,\n",
        "        y,\n",
        "        test_size=TEST_SIZE,\n",
        "        stratify=y,\n",
        "        random_state=RANDOM_STATE,\n",
        "    )\n",
        "\n",
        "    rows = []\n",
        "\n",
        "    fitted_models = {}\n",
        "\n",
        "    for model_name, model in build_models(\n",
        "        fingerprint_features,\n",
        "        descriptor_features,\n",
        "    ).items():\n",
        "\n",
        "        print(f\"Training {model_name}...\")\n",
        "\n",
        "        model.fit(x_train, y_train)\n",
        "\n",
        "        fitted_models[model_name] = model\n",
        "\n",
        "        y_pred = model.predict(x_test)\n",
        "        y_score = model.predict_proba(x_test)[:, 1]\n",
        "\n",
        "        cm = confusion_matrix(y_test, y_pred)\n",
        "\n",
        "        plot_confusion_matrix(\n",
        "            cm,\n",
        "            model_name,\n",
        "            OUTPUT_DIR / f\"{model_name.lower()}_confusion_matrix.png\",\n",
        "        )\n",
        "\n",
        "        roc_auc = plot_roc_curve(\n",
        "            y_test,\n",
        "            y_score,\n",
        "            model_name,\n",
        "            OUTPUT_DIR / f\"{model_name.lower()}_roc_curve.png\",\n",
        "        )\n",
        "\n",
        "        rows.append(\n",
        "            {\n",
        "                \"model\": model_name,\n",
        "                \"accuracy\": accuracy_score(y_test, y_pred),\n",
        "                \"precision\": precision_score(y_test, y_pred, zero_division=0),\n",
        "                \"recall\": recall_score(y_test, y_pred, zero_division=0),\n",
        "                \"f1_score\": f1_score(y_test, y_pred, zero_division=0),\n",
        "                \"roc_auc\": roc_auc,\n",
        "            }\n",
        "        )\n",
        "\n",
        "    results = (\n",
        "        pd.DataFrame(rows)\n",
        "        .sort_values(\"roc_auc\", ascending=False)\n",
        "        .reset_index(drop=True)\n",
        "    )\n",
        "\n",
        "    results.to_csv(\n",
        "        OUTPUT_DIR / \"06_model_comparison_metrics.csv\",\n",
        "        index=False,\n",
        "    )\n",
        "\n",
        "    print(results)\n",
        "\n",
        "    if \"CatBoost\" in fitted_models:\n",
        "        generate_shap_summary(\n",
        "            fitted_models[\"CatBoost\"],\n",
        "            x_test,\n",
        "            fingerprint_features,\n",
        "            descriptor_features,\n",
        "            \"CatBoost\",\n",
        "        )\n",
        "\n",
        "    if \"XGBoost\" in fitted_models:\n",
        "        generate_shap_summary(\n",
        "            fitted_models[\"XGBoost\"],\n",
        "            x_test,\n",
        "            fingerprint_features,\n",
        "            descriptor_features,\n",
        "            \"XGBoost\",\n",
        "        )\n",
        "\n",
        "    print(\"\\nSHAP analysis completed.\")\n",
        "    print(f\"Outputs saved to:\\n{OUTPUT_DIR}\")\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    },
    {
      "cell_type": "markdown",
      "id": "12ea1f65",
      "metadata": {
        "id": "12ea1f65"
      },
      "source": [
        "## 06a_ADMET_SHAP_breakdown.py"
      ]
    },
    {
      "cell_type": "code",
      "execution_count": 19,
      "id": "45ce5239",
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "45ce5239",
        "outputId": "b6693dca-1d89-4945-ff7a-3f26198b3804"
      },
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "ADMET + SHAP breakdown completed successfully.\n",
            "Candidate rows: 31\n",
            "Selected rows for SHAP panels: 3\n",
            "Outputs saved to: /content/outputs/admet_shap_breakdown\n"
          ]
        }
      ],
      "source": [
        "import os\n",
        "\"\"\"ADMET-likeness triage and SHAP breakdown figures for shortlisted RecA-TB FDA candidates.\n",
        "\n",
        "This script adds a lightweight ADMET-likeness screen and local SHAP breakdown\n",
        "for FDA/repurposing candidates predicted against RecA-TB.\n",
        "\n",
        "Main fixes:\n",
        "- Uses paths relative to this script folder.\n",
        "- Supports both old and new workflow output folders.\n",
        "- Does not crash if a structure image is missing; it creates a placeholder panel.\n",
        "- Automatically selects available top candidates if SELECTED_CIDS are absent.\n",
        "- Handles missing ADMET/docking columns more safely.\n",
        "\"\"\"\n",
        "\n",
        "from __future__ import annotations\n",
        "\n",
        "from pathlib import Path\n",
        "\n",
        "import matplotlib\n",
        "matplotlib.use(\"Agg\")\n",
        "\n",
        "import matplotlib.image as mpimg\n",
        "import matplotlib.pyplot as plt\n",
        "import numpy as np\n",
        "import pandas as pd\n",
        "import shap\n",
        "from matplotlib import patches\n",
        "from xgboost import DMatrix, XGBClassifier\n",
        "\n",
        "\n",
        "# Check if running in Google Colab\n",
        "if 'google.colab' in str(get_ipython()):\n",
        "    SCRIPT_DIR = Path('/content')\n",
        "else:\n",
        "    SCRIPT_DIR = Path(__file__).resolve().parent\n",
        "\n",
        "TRAINING_DATA_CANDIDATES = [\n",
        "    SCRIPT_DIR / \"03_recA_low_variance_filtered.csv\", # Added this path\n",
        "    SCRIPT_DIR / \"outputs\" / \"feature_selection\" / \"03_recA_low_variance_filtered.csv\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"recA_chembl\" / \"feature_selection\" / \"recA_low_variance_filtered.csv\",\n",
        "]\n",
        "\n",
        "F_SCORE_CANDIDATES = [\n",
        "    SCRIPT_DIR / \"03_recA_fscore_ranking.csv\", # Added this path\n",
        "    SCRIPT_DIR / \"outputs\" / \"feature_selection\" / \"03_recA_fscore_ranking.csv\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"recA_chembl\" / \"feature_selection\" / \"recA_fscore_ranking.csv\",\n",
        "]\n",
        "\n",
        "FDA_FINGERPRINT_CANDIDATES = [\n",
        "    SCRIPT_DIR / \"05_fda_combined_fingerprints.csv\", # Added this path\n",
        "    SCRIPT_DIR / \"outputs\" / \"fda_prediction\" / \"05_fda_combined_fingerprints.csv\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"recA_chembl\" / \"fda_prediction\" / \"fda_combined_fingerprints.csv\",\n",
        "    SCRIPT_DIR / \"actual_reca_fda_prediction_research_files\" / \"data\" / \"fda_combined_fingerprints.csv\",\n",
        "]\n",
        "\n",
        "FDA_DOCKING_CANDIDATES = [\n",
        "    SCRIPT_DIR / \"05_fda_predictions_with_docking.csv\", # Added this path\n",
        "    SCRIPT_DIR / \"outputs\" / \"fda_prediction\" / \"05_fda_predictions_with_docking.csv\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"fda_prediction\" / \"05_fda_recA_predictions.csv\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"recA_chembl\" / \"docking_real\" / \"fda_predictions_with_real_docking.csv\",\n",
        "    SCRIPT_DIR / \"actual_reca_fda_prediction_research_files\" / \"data\" / \"fda_predictions_with_real_docking.csv\",\n",
        "]\n",
        "\n",
        "STRUCTURE_DIRS = [\n",
        "    SCRIPT_DIR / \"outputs\" / \"fda_prediction\" / \"structures\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"recA_chembl\" / \"balanced_457_458\" / \"manuscript_visuals\" / \"structures\",\n",
        "    SCRIPT_DIR / \"outputs\" / \"recA_chembl\" / \"manuscript_visuals\" / \"structures\",\n",
        "    SCRIPT_DIR / \"actual_reca_fda_prediction_research_files\" / \"structures\",\n",
        "]\n",
        "\n",
        "OUTPUT_DIR = SCRIPT_DIR / \"outputs\" / \"admet_shap_breakdown\"\n",
        "\n",
        "TOP_K_FEATURES = 100\n",
        "RANDOM_STATE = 42\n",
        "SELECTED_CIDS = [2794, 60823, 135403821]\n",
        "\n",
        "\n",
        "def first_existing(paths: list[Path], label: str) -> Path:\n",
        "    for path in paths:\n",
        "        if path.exists():\n",
        "            return path\n",
        "\n",
        "    raise FileNotFoundError(\n",
        "        f\"\\nCould not find required file for: {label}\\n\\n\"\n",
        "        + \"Checked paths:\\n\"\n",
        "        + \"\\n\".join(str(path) for path in paths)\n",
        "    )\n",
        "\n",
        "\n",
        "def load_training_data(top_k: int = TOP_K_FEATURES) -> tuple[pd.DataFrame, pd.Series, list[str]]:\n",
        "    training_file = first_existing(TRAINING_DATA_CANDIDATES, \"training low-variance dataset\")\n",
        "    ranking_file = first_existing(F_SCORE_CANDIDATES, \"F-score ranking file\")\n",
        "\n",
        "    training = pd.read_csv(training_file)\n",
        "    ranking = pd.read_csv(ranking_file)\n",
        "\n",
        "    if \"feature\" not in ranking.columns:\n",
        "        raise ValueError(\"F-score ranking file must contain column: feature\")\n",
        "\n",
        "    if \"class\" not in training.columns:\n",
        "        raise ValueError(\"Training dataset must contain column: class\")\n",
        "\n",
        "    selected_features = [\n",
        "        feature\n",
        "        for feature in ranking[\"feature\"].head(top_k).astype(str).tolist()\n",
        "        if feature in training.columns\n",
        "    ]\n",
        "\n",
        "    if not selected_features:\n",
        "        raise ValueError(\"No selected features from F-score ranking were found in the training file.\")\n",
        "\n",
        "    x_train = (\n",
        "        training[selected_features]\n",
        "        .apply(pd.to_numeric, errors=\"coerce\")\n",
        "        .replace([np.inf, -np.inf], np.nan)\n",
        "        .fillna(0)\n",
        "    )\n",
        "\n",
        "    y_train = training[\"class\"].astype(int)\n",
        "\n",
        "    return x_train, y_train, selected_features\n",
        "\n",
        "\n",
        "def load_candidate_frame(selected_features: list[str]) -> pd.DataFrame:\n",
        "    fingerprint_file = first_existing(FDA_FINGERPRINT_CANDIDATES, \"FDA fingerprint file\")\n",
        "    docking_file = first_existing(FDA_DOCKING_CANDIDATES, \"FDA prediction/docking file\")\n",
        "\n",
        "    fingerprint_df = pd.read_csv(fingerprint_file)\n",
        "    candidate_df = pd.read_csv(docking_file)\n",
        "\n",
        "    if \"Name\" not in fingerprint_df.columns:\n",
        "        raise ValueError(\"FDA fingerprint file must contain column: Name\")\n",
        "\n",
        "    fingerprint_df[\"cid\"] = (\n",
        "        fingerprint_df[\"Name\"]\n",
        "        .astype(str)\n",
        "        .str.replace(\"CID\", \"\", regex=False)\n",
        "        .astype(int)\n",
        "    )\n",
        "\n",
        "    if \"cid\" not in candidate_df.columns:\n",
        "        if \"Name\" in candidate_df.columns:\n",
        "            candidate_df[\"cid\"] = (\n",
        "                candidate_df[\"Name\"]\n",
        "                .astype(str)\n",
        "                .str.replace(\"CID\", \"\", regex=False)\n",
        "                .astype(int)\n",
        "            )\n",
        "        else:\n",
        "            raise ValueError(\"Candidate file must contain either 'cid' or 'Name' column.\")\n",
        "\n",
        "    if \"Name\" not in candidate_df.columns:\n",
        "        candidate_df[\"Name\"] = \"CID\" + candidate_df[\"cid\"].astype(str)\n",
        "\n",
        "    for feature in selected_features:\n",
        "        if feature not in fingerprint_df.columns:\n",
        "            fingerprint_df[feature] = 0\n",
        "\n",
        "    aligned_fp = fingerprint_df[[\"Name\", \"cid\", *selected_features]].copy()\n",
        "\n",
        "    candidate_df = candidate_df.drop(\n",
        "        columns=[\"predicted_probability_active\", \"predicted_class\"],\n",
        "        errors=\"ignore\",\n",
        "    )\n",
        "\n",
        "    merged = candidate_df.merge(\n",
        "        aligned_fp,\n",
        "        on=[\"cid\", \"Name\"],\n",
        "        how=\"inner\",\n",
        "    )\n",
        "\n",
        "    if merged.empty:\n",
        "        raise ValueError(\"Candidate merge failed. No matching CID/Name found between FDA fingerprints and candidate table.\")\n",
        "\n",
        "    return merged\n",
        "\n",
        "\n",
        "def build_xgboost_model() -> XGBClassifier:\n",
        "    return XGBClassifier(\n",
        "        n_estimators=250,\n",
        "        max_depth=5,\n",
        "        learning_rate=0.08,\n",
        "        subsample=0.8,\n",
        "        colsample_bytree=0.9,\n",
        "        min_child_weight=3,\n",
        "        reg_lambda=2,\n",
        "        eval_metric=\"logloss\",\n",
        "        random_state=RANDOM_STATE,\n",
        "        n_jobs=1,\n",
        "    )\n",
        "\n",
        "\n",
        "def ensure_numeric_column(df: pd.DataFrame, column: str, default: float = np.nan) -> pd.Series:\n",
        "    if column not in df.columns:\n",
        "        return pd.Series(default, index=df.index)\n",
        "    return pd.to_numeric(df[column], errors=\"coerce\")\n",
        "\n",
        "\n",
        "def add_admet_heuristics(df: pd.DataFrame) -> pd.DataFrame:\n",
        "    out = df.copy()\n",
        "\n",
        "    out[\"xlogp\"] = ensure_numeric_column(out, \"xlogp\")\n",
        "    out[\"tpsa\"] = ensure_numeric_column(out, \"tpsa\")\n",
        "    out[\"hbd\"] = ensure_numeric_column(out, \"hbd\")\n",
        "    out[\"hba\"] = ensure_numeric_column(out, \"hba\")\n",
        "    out[\"rotatable_bonds\"] = ensure_numeric_column(out, \"rotatable_bonds\")\n",
        "    out[\"molecular_weight\"] = ensure_numeric_column(out, \"molecular_weight\")\n",
        "    out[\"binding_affinity_kcal_mol\"] = ensure_numeric_column(out, \"binding_affinity_kcal_mol\")\n",
        "\n",
        "    out[\"lipinski_violations\"] = (\n",
        "        (out[\"molecular_weight\"] > 500).fillna(False).astype(int)\n",
        "        + (out[\"xlogp\"] > 5).fillna(False).astype(int)\n",
        "        + (out[\"hbd\"] > 5).fillna(False).astype(int)\n",
        "        + (out[\"hba\"] > 10).fillna(False).astype(int)\n",
        "    )\n",
        "\n",
        "    out[\"lipinski_pass\"] = out[\"lipinski_violations\"] <= 1\n",
        "    out[\"veber_pass\"] = ((out[\"tpsa\"] <= 140) & (out[\"rotatable_bonds\"] <= 10)).fillna(False)\n",
        "    out[\"egan_like_pass\"] = ((out[\"xlogp\"] <= 5.88) & (out[\"tpsa\"] <= 131.6)).fillna(False)\n",
        "\n",
        "    out[\"admet_support_score\"] = (\n",
        "        out[[\"lipinski_pass\", \"veber_pass\", \"egan_like_pass\"]]\n",
        "        .astype(float)\n",
        "        .mean(axis=1)\n",
        "    )\n",
        "\n",
        "    def admet_label(score: float) -> str:\n",
        "        if score >= 2 / 3:\n",
        "            return \"Supportive\"\n",
        "        if score >= 1 / 3:\n",
        "            return \"Borderline\"\n",
        "        return \"High risk\"\n",
        "\n",
        "    out[\"admet_support\"] = out[\"admet_support_score\"].map(admet_label)\n",
        "\n",
        "    def admet_flags(row: pd.Series) -> str:\n",
        "        flags: list[str] = []\n",
        "\n",
        "        if pd.notna(row[\"molecular_weight\"]) and row[\"molecular_weight\"] > 500:\n",
        "            flags.append(\"high MW\")\n",
        "        if pd.notna(row[\"xlogp\"]) and row[\"xlogp\"] > 5:\n",
        "            flags.append(\"high logP\")\n",
        "        if pd.notna(row[\"hbd\"]) and row[\"hbd\"] > 5:\n",
        "            flags.append(\"high HBD\")\n",
        "        if pd.notna(row[\"hba\"]) and row[\"hba\"] > 10:\n",
        "            flags.append(\"high HBA\")\n",
        "        if pd.notna(row[\"tpsa\"]) and row[\"tpsa\"] > 140:\n",
        "            flags.append(\"high TPSA\")\n",
        "        if pd.notna(row[\"rotatable_bonds\"]) and row[\"rotatable_bonds\"] > 10:\n",
        "            flags.append(\"high flexibility\")\n",
        "\n",
        "        return \", \".join(flags) if flags else \"no major heuristic alert\"\n",
        "\n",
        "    out[\"admet_flags\"] = out.apply(admet_flags, axis=1)\n",
        "\n",
        "    affinity = out[\"binding_affinity_kcal_mol\"]\n",
        "    if affinity.notna().sum() > 1:\n",
        "        out[\"docking_support_norm\"] = ((-affinity) - (-affinity).min()) / (\n",
        "            (-affinity).max() - (-affinity).min() + 1e-12\n",
        "        )\n",
        "    else:\n",
        "        out[\"docking_support_norm\"] = 0.5\n",
        "\n",
        "    prob = out[\"xgb_probability_active\"]\n",
        "    if prob.notna().sum() > 1:\n",
        "        out[\"ml_support_norm\"] = (prob - prob.min()) / (prob.max() - prob.min() + 1e-12)\n",
        "    else:\n",
        "        out[\"ml_support_norm\"] = 0.5\n",
        "\n",
        "    out[\"integrated_support_score\"] = (\n",
        "        0.45 * out[\"docking_support_norm\"].fillna(0.5)\n",
        "        + 0.30 * out[\"ml_support_norm\"].fillna(0.5)\n",
        "        + 0.25 * out[\"admet_support_score\"].fillna(0.0)\n",
        "    )\n",
        "\n",
        "    def confidence_note(row: pd.Series) -> str:\n",
        "        docking_good = pd.notna(row[\"binding_affinity_kcal_mol\"]) and row[\"binding_affinity_kcal_mol\"] <= -7.5\n",
        "        admet_good = row[\"admet_support_score\"] >= 2 / 3\n",
        "        ml_good = row[\"xgb_probability_active\"] >= 0.25\n",
        "\n",
        "        if docking_good and admet_good:\n",
        "            return \"Balanced hit\"\n",
        "        if docking_good and not admet_good:\n",
        "            return \"Docking-strong, ADMET caution\"\n",
        "        if ml_good and admet_good:\n",
        "            return \"ML/ADMET-supported comparator\"\n",
        "        return \"Lower confidence\"\n",
        "\n",
        "    out[\"selection_note\"] = out.apply(confidence_note, axis=1)\n",
        "\n",
        "    return out.sort_values(\n",
        "        [\"integrated_support_score\", \"binding_affinity_kcal_mol\"],\n",
        "        ascending=[False, True],\n",
        "    ).reset_index(drop=True)\n",
        "\n",
        "\n",
        "def save_admet_note() -> None:\n",
        "    text = \"\"\"# ADMET-likeness note\n",
        "\n",
        "This analysis adds an early ADMET-likeness triage before local explanation of candidate RecA-TB predictions.\n",
        "\n",
        "Included:\n",
        "- Lipinski-style oral-likeness violations\n",
        "- Veber-style permeability/flexibility screen\n",
        "- Egan-like polarity/lipophilicity screen\n",
        "\n",
        "Limitations:\n",
        "- This is not a full ADMET prediction platform.\n",
        "- It does not replace pkCSM, SwissADME, ADMETlab, or experimental ADME assays.\n",
        "\n",
        "Interpretation:\n",
        "- Supportive = passes most heuristic filters.\n",
        "- Borderline = one part of the profile needs caution.\n",
        "- High risk = multiple oral-likeness/permeability alerts.\n",
        "\"\"\"\n",
        "    (OUTPUT_DIR / \"admet_method_note.md\").write_text(text, encoding=\"utf-8\")\n",
        "\n",
        "\n",
        "def save_admet_table_figure(df: pd.DataFrame) -> None:\n",
        "    display = df[\n",
        "        [\n",
        "            \"compound_name\",\n",
        "            \"cid\",\n",
        "            \"xgb_probability_active\",\n",
        "            \"binding_affinity_kcal_mol\",\n",
        "            \"lipinski_violations\",\n",
        "            \"veber_pass\",\n",
        "            \"egan_like_pass\",\n",
        "            \"admet_support\",\n",
        "            \"integrated_support_score\",\n",
        "            \"selection_note\",\n",
        "        ]\n",
        "    ].copy()\n",
        "\n",
        "    display.columns = [\n",
        "        \"Compound\",\n",
        "        \"CID\",\n",
        "        \"XGBoost Prob.\",\n",
        "        \"1MO3 Affinity\",\n",
        "        \"Lipinski Viol.\",\n",
        "        \"Veber\",\n",
        "        \"Egan\",\n",
        "        \"ADMET\",\n",
        "        \"Integrated Score\",\n",
        "        \"Interpretation\",\n",
        "    ]\n",
        "\n",
        "    fig, ax = plt.subplots(figsize=(18.2, 5.8))\n",
        "    ax.axis(\"off\")\n",
        "    ax.set_title(\n",
        "        \"ADMET-Likeness Triage for Docked FDA Candidates\",\n",
        "        fontsize=20,\n",
        "        fontweight=\"bold\",\n",
        "        pad=18,\n",
        "    )\n",
        "\n",
        "    cell_text = []\n",
        "    for _, row in display.iterrows():\n",
        "        cell_text.append(\n",
        "            [\n",
        "                str(row[\"Compound\"]),\n",
        "                str(int(row[\"CID\"])),\n",
        "                f\"{row['XGBoost Prob.']:.3f}\",\n",
        "                \"NA\" if pd.isna(row[\"1MO3 Affinity\"]) else f\"{row['1MO3 Affinity']:.3f}\",\n",
        "                int(row[\"Lipinski Viol.\"]),\n",
        "                \"Pass\" if bool(row[\"Veber\"]) else \"Fail\",\n",
        "                \"Pass\" if bool(row[\"Egan\"]) else \"Fail\",\n",
        "                str(row[\"ADMET\"]),\n",
        "                f\"{row['Integrated Score']:.3f}\",\n",
        "                str(row[\"Interpretation\"]),\n",
        "            ]\n",
        "        )\n",
        "\n",
        "    table = ax.table(\n",
        "        cellText=cell_text,\n",
        "        colLabels=list(display.columns),\n",
        "        cellLoc=\"center\",\n",
        "        colLoc=\"center\",\n",
        "        loc=\"center\",\n",
        "        bbox=[0.0, 0.03, 1.0, 0.88],\n",
        "    )\n",
        "\n",
        "    table.auto_set_font_size(False)\n",
        "    table.set_fontsize(10.5)\n",
        "    table.scale(1.0, 1.5)\n",
        "\n",
        "    for (row_idx, col_idx), cell in table.get_celld().items():\n",
        "        if row_idx == 0:\n",
        "            cell.set_text_props(weight=\"bold\", color=\"white\")\n",
        "            cell.set_facecolor(\"#1f4e79\")\n",
        "        else:\n",
        "            cell.set_edgecolor(\"#c7d5e0\")\n",
        "            if col_idx == 7:\n",
        "                label = display.iloc[row_idx - 1][\"ADMET\"]\n",
        "                if label == \"Supportive\":\n",
        "                    cell.set_facecolor(\"#d9f2d9\")\n",
        "                elif label == \"Borderline\":\n",
        "                    cell.set_facecolor(\"#fff2cc\")\n",
        "                else:\n",
        "                    cell.set_facecolor(\"#f8d7da\")\n",
        "            elif col_idx == 9:\n",
        "                note = display.iloc[row_idx - 1][\"Interpretation\"]\n",
        "                if note == \"Balanced hit\":\n",
        "                    cell.set_facecolor(\"#dceeff\")\n",
        "                elif note == \"Docking-strong, ADMET caution\":\n",
        "                    cell.set_facecolor(\"#fdebd0\")\n",
        "            else:\n",
        "                cell.set_facecolor(\"white\")\n",
        "\n",
        "    fig.text(\n",
        "        0.01,\n",
        "        0.0,\n",
        "        \"Heuristic ADMET-likeness is an early triage layer, not a full ADMET prediction platform.\",\n",
        "        fontsize=10.5,\n",
        "        color=\"#3d5a80\",\n",
        "    )\n",
        "\n",
        "    fig.savefig(OUTPUT_DIR / \"candidate_admet_screening.png\", dpi=220, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "\n",
        "def locate_structure_image(cid: int) -> Path | None:\n",
        "    for directory in STRUCTURE_DIRS:\n",
        "        path = directory / f\"CID{cid}.png\"\n",
        "        if path.exists():\n",
        "            return path\n",
        "    return None\n",
        "\n",
        "\n",
        "def create_structure_placeholder(compound_row: pd.Series, output_path: Path) -> None:\n",
        "    fig, ax = plt.subplots(figsize=(4.2, 4.2))\n",
        "    ax.axis(\"off\")\n",
        "    ax.text(\n",
        "        0.5,\n",
        "        0.55,\n",
        "        str(compound_row.get(\"compound_name\", \"Compound\")).title(),\n",
        "        ha=\"center\",\n",
        "        va=\"center\",\n",
        "        fontsize=14,\n",
        "        fontweight=\"bold\",\n",
        "        wrap=True,\n",
        "    )\n",
        "    ax.text(\n",
        "        0.5,\n",
        "        0.40,\n",
        "        f\"CID {int(compound_row['cid'])}\",\n",
        "        ha=\"center\",\n",
        "        va=\"center\",\n",
        "        fontsize=12,\n",
        "    )\n",
        "    ax.text(\n",
        "        0.5,\n",
        "        0.25,\n",
        "        \"Structure image not found\",\n",
        "        ha=\"center\",\n",
        "        va=\"center\",\n",
        "        fontsize=10,\n",
        "        color=\"gray\",\n",
        "    )\n",
        "    fig.savefig(output_path, dpi=220, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "\n",
        "def build_waterfall_explanation(\n",
        "    contribution_row: np.ndarray,\n",
        "    feature_row: pd.Series,\n",
        "    output_path: Path,\n",
        "    max_display: int = 10,\n",
        ") -> shap.Explanation:\n",
        "    explanation = shap.Explanation(\n",
        "        values=np.asarray(contribution_row[:-1]).reshape(-1),\n",
        "        base_values=float(contribution_row[-1]),\n",
        "        data=feature_row.values,\n",
        "        feature_names=list(feature_row.index),\n",
        "    )\n",
        "\n",
        "    fig = plt.figure(figsize=(10.5, 5.8))\n",
        "    shap.plots.waterfall(explanation, max_display=max_display, show=False)\n",
        "    plt.tight_layout()\n",
        "    fig.savefig(output_path, dpi=220, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "    return explanation\n",
        "\n",
        "\n",
        "def save_compound_panel(\n",
        "    compound_row: pd.Series,\n",
        "    structure_path: Path,\n",
        "    waterfall_path: Path,\n",
        "    output_path: Path,\n",
        ") -> None:\n",
        "    fig = plt.figure(figsize=(14, 5.8))\n",
        "    grid = fig.add_gridspec(1, 2, width_ratios=[1.0, 2.25], wspace=0.1)\n",
        "\n",
        "    ax_left = fig.add_subplot(grid[0, 0])\n",
        "    ax_right = fig.add_subplot(grid[0, 1])\n",
        "    ax_left.axis(\"off\")\n",
        "    ax_right.axis(\"off\")\n",
        "\n",
        "    ax_left.imshow(mpimg.imread(structure_path))\n",
        "    ax_right.imshow(mpimg.imread(waterfall_path))\n",
        "\n",
        "    info_lines = [\n",
        "        str(compound_row[\"compound_name\"]).title(),\n",
        "        f\"CID {int(compound_row['cid'])}\",\n",
        "        f\"XGBoost probability: {compound_row['xgb_probability_active']:.3f}\",\n",
        "        \"1MO3 affinity: NA\"\n",
        "        if pd.isna(compound_row[\"binding_affinity_kcal_mol\"])\n",
        "        else f\"1MO3 affinity: {compound_row['binding_affinity_kcal_mol']:.3f} kcal/mol\",\n",
        "        f\"ADMET-likeness: {compound_row['admet_support']}\",\n",
        "        f\"Interpretation: {compound_row['selection_note']}\",\n",
        "    ]\n",
        "\n",
        "    ax_left.text(\n",
        "        0.5,\n",
        "        -0.08,\n",
        "        \"\\n\".join(info_lines),\n",
        "        transform=ax_left.transAxes,\n",
        "        ha=\"center\",\n",
        "        va=\"top\",\n",
        "        fontsize=11.2,\n",
        "        color=\"#14324a\",\n",
        "        wrap=True,\n",
        "    )\n",
        "\n",
        "    fig.suptitle(\n",
        "        f\"Local SHAP Breakdown for {str(compound_row['compound_name']).title()}\",\n",
        "        fontsize=18,\n",
        "        fontweight=\"bold\",\n",
        "        y=0.98,\n",
        "        color=\"#12355b\",\n",
        "    )\n",
        "\n",
        "    fig.savefig(output_path, dpi=220, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "\n",
        "def save_combined_panel(compound_rows: pd.DataFrame) -> None:\n",
        "    if compound_rows.empty:\n",
        "        return\n",
        "\n",
        "    fig = plt.figure(figsize=(15, 5.4 * len(compound_rows)))\n",
        "    grid = fig.add_gridspec(len(compound_rows), 2, width_ratios=[1.0, 2.2], hspace=0.28, wspace=0.08)\n",
        "\n",
        "    for row_idx, (_, row) in enumerate(compound_rows.iterrows()):\n",
        "        cid = int(row[\"cid\"])\n",
        "        structure_path = OUTPUT_DIR / f\"CID{cid}_structure.png\"\n",
        "        waterfall_path = OUTPUT_DIR / f\"CID{cid}_waterfall.png\"\n",
        "\n",
        "        ax_left = fig.add_subplot(grid[row_idx, 0])\n",
        "        ax_right = fig.add_subplot(grid[row_idx, 1])\n",
        "        ax_left.axis(\"off\")\n",
        "        ax_right.axis(\"off\")\n",
        "\n",
        "        ax_left.imshow(mpimg.imread(structure_path))\n",
        "        ax_right.imshow(mpimg.imread(waterfall_path))\n",
        "\n",
        "        info = [\n",
        "            f\"{str(row['compound_name']).title()} (CID {cid})\",\n",
        "            f\"Probability: {row['xgb_probability_active']:.3f}\",\n",
        "            \"1MO3 affinity: NA\"\n",
        "            if pd.isna(row[\"binding_affinity_kcal_mol\"])\n",
        "            else f\"1MO3 affinity: {row['binding_affinity_kcal_mol']:.3f} kcal/mol\",\n",
        "            f\"ADMET-likeness: {row['admet_support']}\",\n",
        "        ]\n",
        "\n",
        "        ax_left.text(\n",
        "            0.5,\n",
        "            -0.08,\n",
        "            \"\\n\".join(info),\n",
        "            transform=ax_left.transAxes,\n",
        "            ha=\"center\",\n",
        "            va=\"top\",\n",
        "            fontsize=10.6,\n",
        "            color=\"#14324a\",\n",
        "            wrap=True,\n",
        "        )\n",
        "\n",
        "    fig.suptitle(\n",
        "        \"SHAP Breakdown of RecA-TB Candidate Predictions\",\n",
        "        fontsize=19,\n",
        "        fontweight=\"bold\",\n",
        "        y=0.995,\n",
        "        color=\"#12355b\",\n",
        "    )\n",
        "\n",
        "    fig.savefig(OUTPUT_DIR / \"top_compound_shap_breakdown.png\", dpi=220, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "\n",
        "def save_summary_card(df: pd.DataFrame) -> None:\n",
        "    fig, ax = plt.subplots(figsize=(12.5, 3.4))\n",
        "    ax.axis(\"off\")\n",
        "    ax.set_xlim(0, 1)\n",
        "    ax.set_ylim(0, 1)\n",
        "\n",
        "    box = patches.FancyBboxPatch(\n",
        "        (0.02, 0.08),\n",
        "        0.96,\n",
        "        0.82,\n",
        "        boxstyle=\"round,pad=0.02,rounding_size=0.03\",\n",
        "        linewidth=1.4,\n",
        "        edgecolor=\"#9bc4cb\",\n",
        "        facecolor=\"#f7fbfc\",\n",
        "    )\n",
        "\n",
        "    ax.add_patch(box)\n",
        "    ax.text(0.04, 0.82, \"ADMET-Integrated Interpretation\", fontsize=18, fontweight=\"bold\", color=\"#12355b\")\n",
        "\n",
        "    balanced = df[df[\"selection_note\"] == \"Balanced hit\"][\"compound_name\"].astype(str).str.title().tolist()\n",
        "    caution = df[df[\"selection_note\"] == \"Docking-strong, ADMET caution\"][\"compound_name\"].astype(str).str.title().tolist()\n",
        "    comparator = df[df[\"selection_note\"] == \"ML/ADMET-supported comparator\"][\"compound_name\"].astype(str).str.title().tolist()\n",
        "\n",
        "    lines = [\n",
        "        f\"Balanced hits: {', '.join(balanced) if balanced else 'None from this subset'}\",\n",
        "        f\"Docking-strong but ADMET-caution: {', '.join(caution) if caution else 'None'}\",\n",
        "        f\"ML/ADMET-supported comparator: {', '.join(comparator) if comparator else 'None'}\",\n",
        "    ]\n",
        "\n",
        "    for idx, line in enumerate(lines):\n",
        "        ax.text(0.05, 0.60 - idx * 0.18, f\"- {line}\", fontsize=13, color=\"#2c3e50\", va=\"center\")\n",
        "\n",
        "    ax.text(\n",
        "        0.05,\n",
        "        0.10,\n",
        "        \"This screen combines QSAR probability, docking strength, and simple oral-likeness heuristics.\",\n",
        "        fontsize=11.2,\n",
        "        color=\"#486581\",\n",
        "    )\n",
        "\n",
        "    fig.savefig(OUTPUT_DIR / \"admet_integrated_interpretation.png\", dpi=220, bbox_inches=\"tight\")\n",
        "    plt.close(fig)\n",
        "\n",
        "\n",
        "def select_candidate_rows(candidate_frame: pd.DataFrame) -> pd.DataFrame:\n",
        "    available_selected = candidate_frame[candidate_frame[\"cid\"].isin(SELECTED_CIDS)].copy()\n",
        "\n",
        "    if not available_selected.empty:\n",
        "        ordered_cids = [cid for cid in SELECTED_CIDS if cid in set(available_selected[\"cid\"])]\n",
        "        return available_selected.set_index(\"cid\").loc[ordered_cids].reset_index()\n",
        "\n",
        "    return candidate_frame.head(3).copy()\n",
        "\n",
        "\n",
        "def main() -> None:\n",
        "    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)\n",
        "\n",
        "    x_train, y_train, selected_features = load_training_data()\n",
        "    candidate_frame = load_candidate_frame(selected_features)\n",
        "\n",
        "    model = build_xgboost_model()\n",
        "    model.fit(x_train, y_train)\n",
        "\n",
        "    x_candidates = (\n",
        "        candidate_frame[selected_features]\n",
        "        .apply(pd.to_numeric, errors=\"coerce\")\n",
        "        .replace([np.inf, -np.inf], np.nan)\n",
        "        .fillna(0)\n",
        "    )\n",
        "\n",
        "    candidate_frame[\"xgb_probability_active\"] = model.predict_proba(x_candidates)[:, 1]\n",
        "    candidate_frame[\"xgb_predicted_class\"] = np.where(\n",
        "        candidate_frame[\"xgb_probability_active\"] >= 0.5,\n",
        "        \"active_like\",\n",
        "        \"inactive_like\",\n",
        "    )\n",
        "\n",
        "    candidate_frame = add_admet_heuristics(candidate_frame)\n",
        "\n",
        "    candidate_frame.to_csv(OUTPUT_DIR / \"candidate_admet_screening.csv\", index=False)\n",
        "\n",
        "    save_admet_note()\n",
        "    save_admet_table_figure(candidate_frame)\n",
        "    save_summary_card(candidate_frame)\n",
        "\n",
        "    contribution_matrix = model.get_booster().predict(\n",
        "        DMatrix(x_candidates, feature_names=list(x_candidates.columns)),\n",
        "        pred_contribs=True,\n",
        "    )\n",
        "\n",
        "    selected_rows = select_candidate_rows(candidate_frame)\n",
        "\n",
        "    for _, row in selected_rows.iterrows():\n",
        "        cid = int(row[\"cid\"])\n",
        "\n",
        "        structure_copy = OUTPUT_DIR / f\"CID{cid}_structure.png\"\n",
        "        structure_path = locate_structure_image(cid)\n",
        "\n",
        "        if structure_path is None:\n",
        "            create_structure_placeholder(row, structure_copy)\n",
        "        else:\n",
        "            structure_copy.write_bytes(structure_path.read_bytes())\n",
        "\n",
        "        idx = candidate_frame.index[candidate_frame[\"cid\"] == cid][0]\n",
        "        waterfall_path = OUTPUT_DIR / f\"CID{cid}_waterfall.png\"\n",
        "\n",
        "        build_waterfall_explanation(\n",
        "            contribution_matrix[idx],\n",
        "            x_candidates.iloc[idx],\n",
        "            waterfall_path,\n",
        "            max_display=10,\n",
        "        )\n",
        "\n",
        "        panel_path = OUTPUT_DIR / f\"CID{cid}_structure_and_shap_breakdown.png\"\n",
        "\n",
        "        save_compound_panel(\n",
        "            row,\n",
        "            structure_copy,\n",
        "            waterfall_path,\n",
        "            panel_path,\n",
        "        )\n",
        "\n",
        "    save_combined_panel(selected_rows)\n",
        "\n",
        "    print(\"ADMET + SHAP breakdown completed successfully.\")\n",
        "    print(f\"Candidate rows: {len(candidate_frame)}\")\n",
        "    print(f\"Selected rows for SHAP panels: {len(selected_rows)}\")\n",
        "    print(f\"Outputs saved to: {OUTPUT_DIR}\")\n",
        "\n",
        "\n",
        "if __name__ == \"__main__\":\n",
        "    main()"
      ]
    }
  ],
  "metadata": {
    "colab": {
      "provenance": [],
      "include_colab_link": true
    },
    "language_info": {
      "name": "python"
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 5
}
